In [4]:
import numpy as np

np.identity(3)
np.zeros([3,3])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.random.rand(3,3)

array([[0.84754858, 0.58438268, 0.56915541],
       [0.14727629, 0.8207591 , 0.37446578],
       [0.19977721, 0.51951161, 0.0363234 ]])

In [6]:
np.asanyarray([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
A = np.asarray([1,2,3,4]).reshape(2,2)
A_INV = np.linalg.inv(A)
print(A_INV)
print(np.dot(A,A_INV))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [ ]:
# pose describtion

np.asarray([1.0,1.0,1.0]).reshape(3,1)


In [8]:
import math
import numpy as np
theta = math.radians(45)
R_AB = np.asarray([math.cos(theta), -math.sin(theta), 0,
                   math.sin(theta), math.cos(theta),  0,
                   0,               0,                1
                  ]).reshape(3,3)
print(R_AB)


[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [9]:
import math
import numpy as np
theta = math.radians(180)
# x axis 180 grad
R_BC = np.asarray([1,0,0,
                   0,math.cos(theta),-math.sin(theta),
                   0,math.sin(theta),math.cos(theta)]).reshape(3,3)
R_BP = R_BC*np.identity(3)
print("旋转矩阵R_BP：\n",R_BP)


旋转矩阵R_BP：
 [[ 1.  0.  0.]
 [ 0. -1. -0.]
 [ 0.  0. -1.]]


In [10]:
P_BC = np.asarray([0,0,3]).reshape(3,1)
P_CP = np.asarray([2,1,2]).reshape(3,1)
P_BP = np.add(np.dot(R_BC,P_CP),P_BC)
print("位置矢量P_BP:\n",P_BP.T)


位置矢量P_BP:
 [[ 2. -1.  1.]]


In [13]:
import transforms3d as tfs
import numpy as np 
# 四元数转旋转矩阵
tfs.quaternions.quat2mat([1,0,0,0])
# 旋转矩阵转四元数
tfs.quaternions.mat2quat(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))
# 固定轴欧拉角转四元数
tfs.euler.euler2quat(0,0,0,"sxyz")
# 四元数转固定轴欧拉角
tfs.euler.quat2euler([1,0,0,0],"sxyz")
# 固定轴欧拉角转旋转矩阵
tfs.euler.euler2mat(0,0,0,"sxyz")
# 旋转矩阵转固定轴欧拉角
tfs.euler.mat2euler(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]),"sxyz")
# 固定轴欧拉角轴角
tfs.euler.euler2axangle(0,0,0,"sxyz")
# 轴角转固定轴欧拉角
tfs.euler.axangle2euler([1,0,0],0.5,"sxyz")
# 轴角转旋转矩阵
tfs.axangles.axangle2mat([1,0,0],0.5)
# 旋转矩阵转轴角
tfs.axangles.mat2axangle(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))

(array([0., 0., 1.]), 0.0)