In [4]:
import numpy as np

np.identity(3)
np.zeros([3,3])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.random.rand(3,3)

array([[0.84754858, 0.58438268, 0.56915541],
       [0.14727629, 0.8207591 , 0.37446578],
       [0.19977721, 0.51951161, 0.0363234 ]])

In [6]:
np.asanyarray([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
A = np.asarray([1,2,3,4]).reshape(2,2)
A_INV = np.linalg.inv(A)
print(A_INV)
print(np.dot(A,A_INV))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
